### ISSUE TITLE
推理报错

### ISSUE THREAD

**Issue by RuoyuWang-2077** [zjukg/KnowPAT#11]
![image](https://github.com/zjukg/KnowPAT/assets/95166856/866bcdc8-5ddb-44b5-834d-2c52c9672fd5)
我训练完的checkpoint_name如下
![image](https://github.com/zjukg/KnowPAT/assets/95166856/c7c1f28f-8eb3-4140-9219-acc519ea3744)
base_path结构如下
![image](https://github.com/zjukg/KnowPAT/assets/95166856/6c0f8458-97cd-4fd6-bda6-643a91565dcb)

**Comment by ghost** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。

**Comment by Zhang-Each** [comment]
应该是checkpoint的路径填写存在问题

**Comment by RuoyuWang-2077** [comment]
我第一步训练完的模型保存在了export SAVE_PATH="/root/KnowPAT/save2"里面
然后inference中修改了    checkpoint_name = "/root/KnowPAT/save2"
    lora_weights = "".format(checkpoint_name) 这个路径是这么填吗

**Comment by Zhang-Each** [comment]
理论上这样是没问题的，但你的报错里显示没有找到config文件，所以路径还是有问题，可以相对路径绝对路径都试一试
