### ISSUE TITLE
RJUA对应用的什么知识图谱？是否提供下载？

### ISSUE THREAD

**Issue by zhxfei** [zjukg/KnowPAT#13]
如标题

**Comment by ghost** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。

**Comment by Zhang-Each** [comment]
RJUA使用的知识库是数据集自带的相关context，可以在RJUA原仓库提供的数据集中找到。https://github.com/alipay/RJU_Ant_QA

**Comment by zhxfei** [comment]
OK，谢谢，已找到
