### ISSUE TITLE
请问part1 unsupervised triple linking部分的代码在哪里呀？

### ISSUE THREAD

**Issue by yikenie** [zjukg/KnowPAT#2]
请问是怎么实现的呢？我在其他地方看到了一篇关于直接检索的文章，但是他没有给出代码

**Comment by Zhang-Each** [comment]
你好，unsupervised triple linking这一部分的代码涉及到保密数据，因此暂时没有公开，您可以按照论文里描述的方法，通过基于文本相似度的top-k召回检索对应的知识。后续我们会进一步整理代码并上传，感谢您的支持。

**Comment by ghost** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，现在无法亲自回复您的邮件。我会尽快给您回复。

**Comment by Zhang-Each** [comment]
你好，我们已经上传了三元组检索的这一部分代码，位于utils/目录中，你可以尝试在自己的数据集上使用
