### ISSUE TITLE
请问评估的代码能放出来吗？

### ISSUE THREAD

**Issue by jinlong7790** [zjukg/KnowPAT#5]

**Comment by Zhang-Each** [comment]
你好，文本相似度评价相关的指标如BLEU、ROUGE等github和开源库如scikit中有非常多的开源实现，可以自行调用

**Comment by jinlong7790** [comment]
我不会，可以具体点帮助我吗？万分感谢

**Comment by Zhang-Each** [comment]
你好，nltk库中nltk.translate直接提供了sentence_bleu，sentence_chrf，meteor_score等指标的计算api，可以直接参考其相关文档调用执行。

https://www.nltk.org/api/nltk.translate.html
