### ISSUE TITLE
请问论文中提到的使用了经过微调后的Atom-7B-cha模型作为基础模型，有这部分微调的代码吗？这个和论文中的损失函数Lft+Lalign有区别吗？

### ISSUE THREAD

**Issue by jinlong7790** [zjukg/KnowPAT#7]
Meanwhile,the Atom-7B-chat is first fine-tuned on our cloud product documents which is a domain corpus to enable the backbone model with a basic understanding of the domain concepts. We name this model Atom-7B-CP and employ this fine-tuned version as our backbone

**Comment by Zhang-Each** [comment]
这个过程就是使用了对应领域内的数据进行了增量预训练，由于涉及到商业数据无法公开这部分代码，可以参考各类Llama+LoRA微调的开源repo实现这一过程，当然对于非domain-specific的任务来说，没有这一过程也是可以的，只不过性能会有所下降。
