### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.

### ISSUE THREAD

**Issue by wmm228** [zjukg/KnowPAT#8]
您好，我想请问，我在运行inference.py文件时报了这个错误：huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: ''.
请问 checkpoint_name=YOUR SAVE PATH是一个什么样的路径，base_path是LLAMA的路径吗？ 为什么这里lora_weights = "".format(checkpoint_name)格式化字符串前面是一个空串呀？
能否指点一下，谢谢啦！
![1](https://github.com/zjukg/KnowPAT/assets/138777018/879b09d9-9ce6-4e59-be97-e3cede5fac88)

**Comment by wmm228** [comment]
![image](https://github.com/zjukg/KnowPAT/assets/138777018/05b78cbb-bfe0-4272-9aae-1a300542cc90)

**Comment by Zhang-Each** [comment]
你好，我们也没碰到过此类问题，应该是huggingface库本身存在的问题

**Comment by wmm228** [comment]
好的，能否请您在解释一下 checkpoint_name=YOUR SAVE PATH应该是存放什么的路径，lora_weights = "".format(checkpoint_name)格式化字符串前面是一个空串是正确的，对吗？感谢您的回答！

**Comment by Zhang-Each** [comment]
应该填写LORA权重的路径

**Comment by wmm228** [comment]
好的谢谢
